domain: "blog.nietaanraken.nl"

remote_theme: "jekyll/minima"

title: "Blog by Joren Vrancken"
description: "Blog by Joren Vrancken"
author:
  name: "Joren Vrancken"
  email: "jorenvrancken@gmail.com"

header_pages:
  - "about.md"

plugins:
  - "jekyll-redirect-from"
  - "jekyll-feed"

permalink: "/posts/:title/"
