---

services:
  jekyll:
    image: "jekyll/jekyll:latest"
    command: "jekyll serve --watch --drafts"
    # command: "bundle update --all"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ".:/srv/jekyll"
